# @package _global_
model:
  charset_train: >
    0123456789۰۱۲۳۴۵۶۷۸۹
    اآأؤإءئۓۂئےۍېىيےی
    بپڀتٹثٿجچحخدڈذڎرڑزژسشصضطظعغفقڤڠݢکكڭگڬلمنںوۏههةۃۀہھ
    ڽضئکڤݢۏ
    -‌!"#$%&'()*+,./:;<=>?@[\\]^_`{|}~
  charset_test: ${model.charset_train}
